<html><head><meta charset="utf-8"/><title>Test Report</title><style type="text/css">html, body {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 1rem;
	margin: 0;
	padding: 0;
	color: #333;
}
body {
	padding: 1rem;
	font-size: 0.85rem;
}
header {
	display: flex;
	align-items: center;
}
#title {
	margin: 0;
	flex-grow: 1;
}
#logo {
	height: 4rem;
}
#timestamp {
	font-weight: bold;
	color: #666;
	margin-bottom: 0.5rem;
}
#summary {
	color: #999;
	margin-bottom: 1rem;
}
.suite-info {
	padding: 1rem;
	background-color: #eee;
	border-bottom: 2px solid #999;
	color: #999;
	display: flex;
	align-items: center;
}
.suite-info .suite-path {
	font-weight: bold;
	word-break: break-all;
	flex-grow: 1;
}
.suite-info .suite-time {
	margin-left: 0.5rem;
	padding: 0.2rem 0.3rem;
	font-size: 0.75rem;
}
.suite-info .suite-time.warn {
	background-color: #D8000C;
	color: #fff;
}
.suite-table {
	width: 100%;
	font-size: 0.85rem;
	margin-bottom: 1em;
}
.suite-table td {
	padding: 0.5rem;
}
.suite-table tr.passed {
	background-color: #DFF2BF;
	color: #4F8A10;
}
.suite-table tr.pending {
	background-color: #FEEFB3;
	color: #9F6000;
}
.suite-table tr.failed {
	background-color: #FFBABA;
	color: #D8000C;
}
.suite-table td {
	font-size: 0.85rem;
	border-bottom: 1px solid #aaa;
	vertical-align: top;
}
.suite-table td.suite {
	font-weight: bold;
	width: 20%;
}
.suite-table td.test {
	font-style: italic;
	width: 60%;
}
.suite-table td.test .failureMsg {
	font-size: 1rem;
	white-space: pre-wrap;
	white-space: -moz-pre-wrap;
	white-space: -pre-wrap;
	white-space: -o-pre-wrap;
	word-wrap: break-word;
}
.suite-table td.result {
	width: 20%;
	text-align: right;
}

/* CONSOLE LOGS */
.suite-consolelog {
	margin-bottom: 2rem;
	padding: 1rem;
	background-color: #efefef;
}
.suite-consolelog-header {
	font-weight: bold;
}
.suite-consolelog-item {
	padding: 0.5rem;
}
.suite-consolelog-item pre {
	margin: 0;
}
.suite-consolelog-item-origin {
	color: #777;
	font-weight: bold;
}
.suite-consolelog-item-message {
	color: #000;
	font-size: 1rem;
	padding: 0 0.5rem;
}
</style></head><body><div id="jesthtml-content"><header><h1 id="title">Test Report</h1></header><div id="metadata-container"><div id="timestamp">Start: 2019-10-15 08:53:10</div><div id="summary">158 tests -- 44 passed / 77 failed / 37 pending</div></div><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\feedback\feedback.test.js</div><div class="suite-time">4.117s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="passed"><td class="suite">Feedback</td><td class="test">should create feedback entry<div class="failureMessages"/></td><td class="result">passed in 0.195s</td></tr></table><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\reference\reference.test.js</div><div class="suite-time">4.633s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch services<div class="failureMessages"/></td><td class="result">passed in 0.28s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch Non-CQC main services by category<div class="failureMessages"/></td><td class="result">passed in 0.023s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch CQC main services by category<div class="failureMessages"/></td><td class="result">passed in 0.018s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch jobs<div class="failureMessages"/></td><td class="result">passed in 0.031s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch Local Authorities<div class="failureMessages"/></td><td class="result">passed in 0.052s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch Primary Authority<div class="failureMessages"/></td><td class="result">passed in 0.075s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch Ethnicities<div class="failureMessages"/></td><td class="result">passed in 0.033s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch Nationalities<div class="failureMessages"/></td><td class="result">passed in 0.064s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch countries<div class="failureMessages"/></td><td class="result">passed in 0.051s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch qualifications<div class="failureMessages"/></td><td class="result">passed in 0.03s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch qualifications<div class="failureMessages"/></td><td class="result">passed in 0.054s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch worker leave reasons<div class="failureMessages"/></td><td class="result">passed in 0.037s</td></tr><tr class="passed"><td class="suite">Expected reference services</td><td class="test">should fetch service users<div class="failureMessages"/></td><td class="result">passed in 0.029s</td></tr></table><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js</div><div class="suite-time warn">11.442s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should create a non-CQC registation<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should login using the given username<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:98:41)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the name<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:142:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the Main Service<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:236:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="pending"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the employer type<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the number of staff<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:533:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update 'other' services<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:657:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update service users<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:851:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update 'service capacities<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:1012:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the sharing options<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:1243:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the Local Authorities Share Options<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:1457:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should update the number of vacancies, starters and leavers<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:1651:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should get the Establishment<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:2196:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="pending"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should get establishment with property history<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should get user with timeline history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:2293:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should get user with full history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\establishments\establishment.test.js:2325:35)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">establishment &gt; Non CQC Establishment</td><td class="test">should report on response times<div class="failureMessages"/></td><td class="result">passed in 0.08s</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Employer Type</td><td class="test">should fail (401) when attempting to update 'employer type' without passing Authorization header<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Employer Type</td><td class="test">should fail (403) when attempting to update 'employer type' passing Authorization header with mismatched establishment id<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Employer Type</td><td class="test">should fail (503) when attempting to update 'employer type' with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Employer Type</td><td class="test">should fail (400) when attempting to update 'employer type' with unexpected employer type<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Employer Type</td><td class="test">should fail (400) when attempting to update 'employer type' with unexpected request format (JSON Schema)<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (401) when attempting to update 'other services' without passing Authorization header<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (403) when attempting to update 'other services' passing Authorization header with mismatched establishment id<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (503) when attempting to update 'other services' with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (400) when trying to update 'other services' with duplicates<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (400) when trying to update 'other services' using 'main service'<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Other Services</td><td class="test">should fail (400) when attempting to update 'other services' with unexpected request format (JSON Schema)<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Service Capacities</td><td class="test">should fail (401) when attempting to update 'services capacities' without passing Authorization header<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Service Capacities</td><td class="test">should fail (403) when attempting to update 'services capacities' passing Authorization header with mismatched establishment id<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Service Capacities</td><td class="test">should fail (503) when attempting to update 'services capacities' with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Service Capacities</td><td class="test">should fail (400) when trying to update 'services capacities' with duplicates<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">establishment &gt; Establishment forced failures &gt; Service Capacities</td><td class="test">should fail (400) when attempting to update 'services capacities' with unexpected request format (JSON Schema)<div class="failureMessages"/></td><td class="result">pending</td></tr></table><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js</div><div class="suite-time warn">13.224s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should create a Worker<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:127:40)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's mandatory properties<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:252:40)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Approved Mental Health Worker property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:455:42)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Main Job Start Date property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's NI Number property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's DOB property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's postcode property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's gender<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's disability<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's ethnicity<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's nationality<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's country of birth<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's recruited from<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's British Citizenship<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Year of Arrival<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Social Care Start Date<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Other Jobs<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Sick Days<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's zero hours contract<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Weekly Average Hours<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Weekly Contracted Hours<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Annual/Hourly Rate<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Care Certificate<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Apprenticeship Training<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Qualification In Social Care<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Social Care qualifications<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Other Qualification<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Highest (other) qualifications<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should update a Worker's Completed status<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should return a list of Workers<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:3796:40)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should fetch a single worker<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:3827:38)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should have creation and update change history<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:3878:40)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">should have delete worker<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\workers\worker.test.js:3938:40)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">worker &gt; Establishment 1 against http://localhost:3000/api</td><td class="test">Should report on response times<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 400 "Bad Request"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; GET</td><td class="test">should fail (503) when attempting to fetch worker with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; GET</td><td class="test">should fail (404) when attempting to fetch worker with establishment id no longer exists (but JWT token still valid)<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; POST</td><td class="test">should fail (503) when attempting to create worker with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; POST</td><td class="test">should fail (409) when attempting to create worker with duplicate name/id for the same establishment<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; POST</td><td class="test">should fail (404) when attempting to create worker with establishment id no longer exists (but JWT token still valid)<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; PUT</td><td class="test">should fail (503) when attempting to update worker with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; PUT</td><td class="test">should fail (404) when attempting to update worker with establishment id no longer exists (but JWT token still valid)<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; DELETE</td><td class="test">should fail (401) when attempting to delete worker without passing Authorization header<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; DELETE</td><td class="test">should fail (403) when attempting to delete worker passing Authorization header with mismatched establishment id<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; DELETE</td><td class="test">should fail (403) when attempting to delete worker not belong to given establishment with id<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; DELETE</td><td class="test">should fail (503) when attempting to delete worker with unexpected server error<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">worker &gt; Worker forced failures &gt; DELETE</td><td class="test">should fail (404) when attempting to delete worker with establishment id no longer exists (but JWT token still valid)<div class="failureMessages"/></td><td class="result">pending</td></tr></table><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\registrations\registration.test.js</div><div class="suite-time warn">14.44s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="passed"><td class="suite">Registrations</td><td class="test">should create a non-CQC registation<div class="failureMessages"/></td><td class="result">passed in 1.419s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should create a CQC registation of known location id<div class="failureMessages"/></td><td class="result">passed in 1.48s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should create a second CQC registation of different known location id but same postcode and name<div class="failureMessages"/></td><td class="result">passed in 0.642s</td></tr><tr class="failed"><td class="suite">Registrations</td><td class="test">should fail on CQC if site with location id, postcode and name already existing<div class="failureMessages"><pre class="failureMsg">Error: expect(received).toEqual(expected) // deep equality

Expected: -190
Received: -200
    at Object.toEqual (C:\Users\arussell\Documents\Repos\NMDS\server\test\registrations\registration.test.js:146:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Registrations</td><td class="test">should fail on non-CQC site with postcode and name already existing<div class="failureMessages"><pre class="failureMsg">Error: expect(received).toEqual(expected) // deep equality

Expected: -190
Received: -200
    at Object.toEqual (C:\Users\arussell\Documents\Repos\NMDS\server\test\registrations\registration.test.js:155:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should fail if username is already existing<div class="failureMessages"/></td><td class="result">passed in 0.523s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known service with success<div class="failureMessages"/></td><td class="result">passed in 0.008s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown service with success<div class="failureMessages"/></td><td class="result">passed in 0.008s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known username with success<div class="failureMessages"/></td><td class="result">passed in 0.01s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown username with success<div class="failureMessages"/></td><td class="result">passed in 0.01s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known username via usernameOrPasswword with success<div class="failureMessages"/></td><td class="result">passed in 0.018s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown username via usernameOrPasswword with not found<div class="failureMessages"/></td><td class="result">passed in 0.386s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known email via usernameOrPasswword with success<div class="failureMessages"/></td><td class="result">passed in 0.017s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown email via usernameOrPasswword with not found<div class="failureMessages"/></td><td class="result">passed in 0.017s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known establishment by name with success<div class="failureMessages"/></td><td class="result">passed in 0.015s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown establishment by name with success<div class="failureMessages"/></td><td class="result">passed in 0.009s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup a known establishment by name and location id with success<div class="failureMessages"/></td><td class="result">passed in 0.011s</td></tr><tr class="passed"><td class="suite">Registrations</td><td class="test">should lookup an unknown establishment by name and location id with success<div class="failureMessages"/></td><td class="result">passed in 0.013s</td></tr></table><div class="suite-info"><div class="suite-path">C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js</div><div class="suite-time warn">14.799s</div></div><table class="suite-table" cellspacing="0" cellpadding="0"><tr class="passed"><td class="suite">Password Resets</td><td class="test">should create a non-CQC registation<div class="failureMessages"/></td><td class="result">passed in 1.229s</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should login to the registered site and primary user should have edit role<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 401 "Unauthorized"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should lookup a known username via usernameOrPasswword with success<div class="failureMessages"/></td><td class="result">passed in 0.629s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should lookup an unknown username via usernameOrPasswword with not found<div class="failureMessages"/></td><td class="result">passed in 0.069s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should lookup a known email via usernameOrPasswword with success<div class="failureMessages"/></td><td class="result">passed in 0.048s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should lookup an unknown email via usernameOrPasswword with not found<div class="failureMessages"/></td><td class="result">passed in 0.541s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should fail to request reset on unknown username with validation err<div class="failureMessages"/></td><td class="result">passed in 0.014s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should succeed to request reset on unknown username or email<div class="failureMessages"/></td><td class="result">passed in 0.067s</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should succeed to request reset on known username<div class="failureMessages"><pre class="failureMsg">Error: expected "Content-Type" header field
    at Test.Object.&lt;anonymous&gt;.Test._assertHeader (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:237:45)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should succeed to request reset on known email<div class="failureMessages"><pre class="failureMsg">Error: expect(received).toHaveProperty(path)

Expected path: "resetLink"
Received path: []

Received value: {}
    at Object.toHaveProperty (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:121:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should fail validation on validating password reset<div class="failureMessages"/></td><td class="result">passed in 0.008s</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should fail on unknown reset uuid on validating password reset<div class="failureMessages"/></td><td class="result">passed in 0.027s</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail on expired token when validating password reset<div class="failureMessages"><pre class="failureMsg">Error: expected "Content-Type" header field
    at Test.Object.&lt;anonymous&gt;.Test._assertHeader (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:237:45)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should return JWT on Authorization header on successfull validating password reset<div class="failureMessages"><pre class="failureMsg">Error: expected "Content-Type" header field
    at Test.Object.&lt;anonymous&gt;.Test._assertHeader (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:237:45)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should not fail on completed token when re-validating password reset<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:190:36)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should fail on reset password if no Authorization header given<div class="failureMessages"/></td><td class="result">passed in 0.004s</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail on reset password if Authorization header if invalid<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 401 "Unauthorized"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail on reset password if no password given<div class="failureMessages"><pre class="failureMsg">Error: expected 400 "Bad Request", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail on reset password if password given fails validation (strength)<div class="failureMessages"><pre class="failureMsg">Error: expected 400 "Bad Request", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should success on reset password if using a valid token and valid password<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:244:36)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Password Resets</td><td class="test">should fail for change password with 401 if no authorization header<div class="failureMessages"/></td><td class="result">passed in 0.004s</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail for change password with 403 if no authorisation header is not a valid logged in JWT<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:290:36)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail for change password with 400 current/new password is not given<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:303:42)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail for change password with 400 new password is not of required complexity<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:325:42)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should fail for change password with 403 if header is good, but current password is incorrect<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:341:42)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Password Resets</td><td class="test">should success in changing user's password<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at IncomingMessage.parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="passed"><td class="suite">Change User Details</td><td class="test">should create a non-CQC registation<div class="failureMessages"/></td><td class="result">passed in 0.424s</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should return a list of all establishment users<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 401 "Unauthorized"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should return a User by uid no history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:458:34)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should return a User by username no history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:500:34)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should get user with property history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:539:34)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update fullname property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update job title property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update email property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update phone property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update security question property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should update security question answer property<div class="failureMessages"><pre class="failureMsg">Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.&lt;anonymous&gt;.Test._assertStatus (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.&lt;anonymous&gt;.Test._assertFunction (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.&lt;anonymous&gt;.Test.assert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:173:18)
    at localAssert (C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:131:12)
    at C:\Users\arussell\Documents\Repos\NMDS\node_modules\supertest\lib\test.js:128:5
    at Test.Object.&lt;anonymous&gt;.Request.callback (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\arussell\Documents\Repos\NMDS\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should get user with timeline history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:1224:34)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="failed"><td class="suite">Change User Details</td><td class="test">should get user with full history<div class="failureMessages"><pre class="failureMsg">Error: expect(received).not.toBeNull()

Received: null
    at Object.toBeNull (C:\Users\arussell\Documents\Repos\NMDS\server\test\accounts\accounts.test.js:1317:34)
    at Object.asyncJestTest (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
    at resolve (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
    at promise.then (C:\Users\arussell\Documents\Repos\NMDS\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)</pre></div></td><td class="result">failed</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should register (part add) new user against existing establishment<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should validate (part add) new user against existing establishment<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should add new user (having been part registered) against existing establishment<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should safely rollback new user on duplicate username<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should add read only user and not be able to add new users<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should edit a pending add user registration, including sending of email<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="pending"><td class="suite">Change User Details</td><td class="test">should edit an existing user but not role<div class="failureMessages"/></td><td class="result">pending</td></tr><tr class="passed"><td class="suite">Change User Details</td><td class="test">should report on response times<div class="failureMessages"/></td><td class="result">passed in 0.074s</td></tr></table></div></body></html>